services:
  posgresql_db:
    image: postgres
    container_name: posgresql_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: aadehamid
      POSTGRES_DB: udacity
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  seed_node:
    image: cassandra
    container_name: cassandra_db
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      # - DS_LICENCE=accept
    # cap_add:
    #   - IPC_LOCK
    # ulimits:
    #   memlock: -1
    restart: always
    volumes:
      - csdata:/hamidadesokan/cassandra

  # studio:
  #   image: "datastax/dse-studio"
  #   container_name: studio
  #   ports:
  #     - "9091:9091"
  #   environment:
  #     - DS_LICENSE=accept
  #   links:
  #     - seed_node

  postgres_jupyter:
    build: .
    container_name: jupyter
    ports:
      - "8888:8888"
    depends_on:
      - posgresql_db
      - seed_node

    volumes:
      - ./python_postgres/python_scripts:/hamidadesokan/src
      - ./cassandra/python_scripts:/hamidadesokan/src
      - ./project_postgres_songs:/hamidadesokan/src


volumes:
  pgdata:
  csdata:
