services:
  posgresql_db:
    image: postgres
    container_name: posgresql_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: aadehamid
      POSTGRES_DB: default_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  postgres_jupyter:
    build: .
    container_name: jupyter
    ports:
      - "8888:8888"
    depends_on:
      - posgresql_db

    volumes:
      - ../../postgresql/:/hamidadesokan/src
volumes:
  pgdata:
