services:

  posgresql:
    image: postgres
    container_name: posgresql_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: aadehamid
      POSTGRES_DB: default_db
    ports:
      - "5432:5432"
    init: true
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /var/run/docker.sock:/var/run/docker.sock
  cassandra:
    image: cassandra
    container_name: cassandra_db

    ports:
      # - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
    init: true
    volumes:
      - cassdata:/var/lib/cassandra/data
      - /var/run/docker.sock:/var/run/docker.sock

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: jupyter
    ports:
      - "8888:8888"
    depends_on:
      - cassandra
      - postgresql

    init: true
    volumes:
      # - ../../:/hamidadesokan/src
      - ../../:/hamidadesokan/src
      - vscode-extensions:/root/.vscode-server/extensions
      - /var/run/docker.sock:/var/run/docker.sock

    command: sleep infinity

volumes:
  cassdata:
  vscode-extensions:
  pgdata:
