services:
  cassandra:
    image: cassandra
    container_name: cassandra_db

    ports:
      # - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
    init: true
    volumes:
      - cassdata:/var/lib/cassandra/data
      - /var/run/docker.sock:/var/run/docker.sock

  jupyter:
    build:
    context: .
    dockerfile: Dockerfile.dev
    container_name: jupyter
    ports:
      - "8888:8888"
    depends_on:
      - cassandra

    init: true
    volumes:
      - ../../:/hamidadesokan/src
      - vscode-extensions:/root/.vscode-server/extensions
      - /var/run/docker.sock:/var/run/docker.sock

    command: sleep infinity

volumes:
  cassdata:
  vscode-extensions:
